### ISSUE TITLE
Error when running from live media

### ISSUE THREAD

**Issue by Dal78** [benapetr/compress#3]
I get the following error when i run this from live install media (Endevour arch based)

```
[liveuser@eos-2021.12.17 bin]$ sudo compress -rdv /mnt/@/
Decompressing folder recursively: /mnt/@/
Decompressing folder recursively: /mnt/@//home
Decompressing folder recursively: /mnt/@//var
Decompressing folder recursively: /mnt/@//var/cache
Decompressing folder recursively: /mnt/@//var/log
Decompressing folder recursively: /mnt/@//var/lib
Decompressing folder recursively: /mnt/@//var/lib/pacman
Decompressing folder recursively: /mnt/@//var/lib/pacman/local
Traceback (most recent call last):
  File "/usr/local/bin/compress", line 189, in <module>
    process_target(item)
  File "/usr/local/bin/compress", line 184, in process_target
    compress_folder(target)
  File "/usr/local/bin/compress", line 120, in compress_folder
    compress_folder(p)
  File "/usr/local/bin/compress", line 120, in compress_folder
    compress_folder(p)
  File "/usr/local/bin/compress", line 120, in compress_folder
    compress_folder(p)
  [Previous line repeated 1 more time]
  File "/usr/local/bin/compress", line 126, in compress_folder
    elif (args.decompress and not test_compress(p)):
  File "/usr/local/bin/compress", line 55, in test_compress
    result = result[:result.index(" ")]
TypeError: argument should be integer or bytes-like object, not 'str'
```

Can you let me know what packages i might be missing or the resolution?

Thx

**Comment by Dal78** [comment]
nvm i fixed it by forcing it to python2
